# We specify volumes in override.yml, because volumes don't work well in a
# docker-in-docker setup (the paths of parent host rarely match the nested containers)
version: "3.9"

services:
  backend:
    command: uvicorn --port 8003 --host 0.0.0.0 --reload main:app
    volumes:
      - ./backend:/app:delegated
      - root-home:/root:delegated
