version: "3.9"

services:
  backend:
    build:
      context: backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8003:8003"
    env_file: .env

  # frontend:
  #   build:
  #     context: frontend
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   ports:
  #     - "3003:80"
  #   volumes:
  #     - ./frontend:/app:delegated
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=production

volumes:
  app-db-data:
  root-home:
