"""add optimized

Revision ID: 82692040bf98
Revises: a483bc80eea3
Create Date: 2023-01-01 15:30:15.969024

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82692040bf98'
down_revision = 'a483bc80eea3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vrp_optimized',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('cost', sa.INTEGER(), nullable=False),
    sa.Column('routes_count', sa.INTEGER(), nullable=False),
    sa.Column('unassigned_count', sa.INTEGER(), nullable=False),
    sa.Column('unassigned', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('routes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('setup', sa.INTEGER(), nullable=False),
    sa.Column('service', sa.INTEGER(), nullable=False),
    sa.Column('duration', sa.INTEGER(), nullable=False),
    sa.Column('waiting_time', sa.INTEGER(), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('loading', sa.INTEGER(), nullable=False),
    sa.Column('solving', sa.INTEGER(), nullable=False),
    sa.Column('delivery', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('amount', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hub_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['hub_id'], ['vrp_hub.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('vrp_optimized')
    # ### end Alembic commands ###
