"""delete data

Revision ID: ee03abf14121
Revises: 1eb5966b4f48
Create Date: 2022-12-24 04:26:53.646768

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ee03abf14121"
down_revision = "1eb5966b4f48"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vrp_data")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vrp_data",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("hub_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("vehicle_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("user_id", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["hub_id"], ["vrp_hub.id"], name="vrp_data_hub_id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="vrp_data_user_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vrp_vehicle.id"],
            name="vrp_data_vehicle_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="vrp_data_pkey"),
        sa.UniqueConstraint("id", name="vrp_data_id_key"),
    )
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "(srid > 0) AND (srid <= 998999)", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    # ### end Alembic commands ###
